# Generated by Django 4.2.1 on 2023-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_forms_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forms',
        ),
    ]
