# Generated by Django 4.2.1 on 2023-07-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=250)),
                ('DOB', models.DateTimeField()),
                ('AGE', models.IntegerField()),
                ('GENDER', models.CharField(max_length=250)),
                ('Phone', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('ADDRESS', models.CharField(max_length=250)),
                ('Department', models.CharField(max_length=250)),
                ('PURPOSE', models.CharField(max_length=250)),
                ('Materials', models.CharField(max_length=250)),
            ],
        ),
    ]
